name: weather
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^4.2.1
  bloc: ^8.0.3
  collection: ^1.16.0
  dartx: ^1.1.0
  dio: ^4.0.6
  dio_cache_interceptor: ^3.3.0
  flutter_bloc: ^8.0.1
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  injectable: ^1.5.3
  intl: ^0.17.0
  json_annotation: ^4.6.0
  pull_to_refresh: ^2.0.0
  retrofit: ^3.0.1+1
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^4.2.0
  build_runner: ^2.2.0
  flutter_gen_runner: ^4.3.0
  flutter_lints: ^2.0.1
  freezed: ^2.1.0+1
  injectable_generator: ^1.5.4
  json_serializable: ^6.3.1
  retrofit_generator: ^4.0.2

flutter_gen:
  output: lib/gen/
  line_length: 80

flutter:
  uses-material-design: true

  assets:
    - assets/images/
